// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8k5P-4gsFpiYuBbwLsqaT8tcKBbRap94',
    appId: '1:420815551365:web:9a3ba47dc88734846be2ec',
    messagingSenderId: '420815551365',
    projectId: 'kidsstuff-4534e',
    authDomain: 'kidsstuff-4534e.firebaseapp.com',
    storageBucket: 'kidsstuff-4534e.appspot.com',
    measurementId: 'G-YK7S8CQY7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0P2QrF_Hz3u009uQUiFqDM_2TO6vjMtk',
    appId: '1:420815551365:android:a4c2765b22bc98a76be2ec',
    messagingSenderId: '420815551365',
    projectId: 'kidsstuff-4534e',
    storageBucket: 'kidsstuff-4534e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXVzKv02YKGy9_vJxYGUtIL8uYkpwgCmk',
    appId: '1:420815551365:ios:7e37183c278fa1c86be2ec',
    messagingSenderId: '420815551365',
    projectId: 'kidsstuff-4534e',
    storageBucket: 'kidsstuff-4534e.appspot.com',
    iosClientId: '420815551365-cha3kbk59j7ep5pcqt5qv2qhj6e9gtur.apps.googleusercontent.com',
    iosBundleId: 'com.example.kidsStuff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXVzKv02YKGy9_vJxYGUtIL8uYkpwgCmk',
    appId: '1:420815551365:ios:7e37183c278fa1c86be2ec',
    messagingSenderId: '420815551365',
    projectId: 'kidsstuff-4534e',
    storageBucket: 'kidsstuff-4534e.appspot.com',
    iosClientId: '420815551365-cha3kbk59j7ep5pcqt5qv2qhj6e9gtur.apps.googleusercontent.com',
    iosBundleId: 'com.example.kidsStuff',
  );
}
